export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1 className="bg-sky-600 text-white py-5 px-5">Header</h1>
        {children}
        <h1 className="bg-green-500 text-stone-200 px-5">Footer</h1>
        </body>
    </html>
  )
}
