import { Metadata } from "next"
import Navbar from "./_lib/navigation/Navbar"

export const metadata:Metadata = {
  title: {
    default:"Next ja classes",
    template:"%s | next.js classes",
    absolute:""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1 className="bg-sky-600 text-white py-5 px-5">
          <Navbar />
        </h1>
        {children}
        <h1 className="bg-green-500 text-stone-200 px-5">Footer</h1>
        </body>
    </html>
  )
}
